services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_USER=${POSTGRESQL_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRESQL_PASSWORD}
      - POSTGRES_DB=${POSTGRESQL_DATABASE}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env.development

  redis:
    image: redis:latest
    container_name: redis_cache
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
